version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=fornece_ai
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
